// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAWWZ9hUDdE7xBxz7DP_2D7jzj62dKSkw',
    appId: '1:195478549484:web:dba36da41e619c232b06c9',
    messagingSenderId: '195478549484',
    projectId: 'taskup-593c0',
    authDomain: 'taskup-593c0.firebaseapp.com',
    storageBucket: 'taskup-593c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-3FbKxKdLra4L0fbYhrv2VM3er82TxA4',
    appId: '1:195478549484:android:62e9a294619dd0e82b06c9',
    messagingSenderId: '195478549484',
    projectId: 'taskup-593c0',
    storageBucket: 'taskup-593c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_NkZ3hCu8hDu8Mu-PgqSetLbyj2UwFmo',
    appId: '1:195478549484:ios:e66130db6d2859852b06c9',
    messagingSenderId: '195478549484',
    projectId: 'taskup-593c0',
    storageBucket: 'taskup-593c0.appspot.com',
    iosBundleId: 'com.example.taskManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_NkZ3hCu8hDu8Mu-PgqSetLbyj2UwFmo',
    appId: '1:195478549484:ios:e66130db6d2859852b06c9',
    messagingSenderId: '195478549484',
    projectId: 'taskup-593c0',
    storageBucket: 'taskup-593c0.appspot.com',
    iosBundleId: 'com.example.taskManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAWWZ9hUDdE7xBxz7DP_2D7jzj62dKSkw',
    appId: '1:195478549484:web:7c77df2cffa048782b06c9',
    messagingSenderId: '195478549484',
    projectId: 'taskup-593c0',
    authDomain: 'taskup-593c0.firebaseapp.com',
    storageBucket: 'taskup-593c0.appspot.com',
  );
}
