// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQNafg_r-LwDydkix9EZV5EuewVR_7Zv8',
    appId: '1:637638792097:web:5693b2186a48d2b4dcb1e0',
    messagingSenderId: '637638792097',
    projectId: 'taskup-20655',
    authDomain: 'taskup-20655.firebaseapp.com',
    storageBucket: 'taskup-20655.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNgd5MEHSzNoGJm9X-HWK_XilfjhNy38Q',
    appId: '1:637638792097:android:941a8975eca9a0c0dcb1e0',
    messagingSenderId: '637638792097',
    projectId: 'taskup-20655',
    storageBucket: 'taskup-20655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT1OuqqcPCA7m9zSzeCrVBPkgO_IPkpRg',
    appId: '1:637638792097:ios:d079b3768c3f9ab4dcb1e0',
    messagingSenderId: '637638792097',
    projectId: 'taskup-20655',
    storageBucket: 'taskup-20655.appspot.com',
    iosBundleId: 'com.example.taskUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT1OuqqcPCA7m9zSzeCrVBPkgO_IPkpRg',
    appId: '1:637638792097:ios:d079b3768c3f9ab4dcb1e0',
    messagingSenderId: '637638792097',
    projectId: 'taskup-20655',
    storageBucket: 'taskup-20655.appspot.com',
    iosBundleId: 'com.example.taskUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQNafg_r-LwDydkix9EZV5EuewVR_7Zv8',
    appId: '1:637638792097:web:16f94510054d6474dcb1e0',
    messagingSenderId: '637638792097',
    projectId: 'taskup-20655',
    authDomain: 'taskup-20655.firebaseapp.com',
    storageBucket: 'taskup-20655.appspot.com',
  );
}
