// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//Auto-generated for firebase operations
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3JzfAB7-KR-q5qQJZNjDtYdjzhPVpZYw',
    appId: '1:466559732753:web:5eade195ee04b5ff8d35b0',
    messagingSenderId: '466559732753',
    projectId: 'taskup-6d6ce',
    authDomain: 'taskup-6d6ce.firebaseapp.com',
    databaseURL: 'https://taskup-6d6ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskup-6d6ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFzSUBCUMpU_BHZ1qYKl1cY0MrIbCFbIY',
    appId: '1:466559732753:android:459b20fbf7a9a9ba8d35b0',
    messagingSenderId: '466559732753',
    projectId: 'taskup-6d6ce',
    databaseURL: 'https://taskup-6d6ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskup-6d6ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOyjvCxLZPALYyN8wdjxoonuV_GHJHBJA',
    appId: '1:466559732753:ios:0e7dd6c7ea97ca2f8d35b0',
    messagingSenderId: '466559732753',
    projectId: 'taskup-6d6ce',
    databaseURL: 'https://taskup-6d6ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskup-6d6ce.appspot.com',
    iosBundleId: 'com.example.taskUpPreAlpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOyjvCxLZPALYyN8wdjxoonuV_GHJHBJA',
    appId: '1:466559732753:ios:0e7dd6c7ea97ca2f8d35b0',
    messagingSenderId: '466559732753',
    projectId: 'taskup-6d6ce',
    databaseURL: 'https://taskup-6d6ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskup-6d6ce.appspot.com',
    iosBundleId: 'com.example.taskUpPreAlpha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3JzfAB7-KR-q5qQJZNjDtYdjzhPVpZYw',
    appId: '1:466559732753:web:c8d2ddc381c52e588d35b0',
    messagingSenderId: '466559732753',
    projectId: 'taskup-6d6ce',
    authDomain: 'taskup-6d6ce.firebaseapp.com',
    databaseURL: 'https://taskup-6d6ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskup-6d6ce.appspot.com',
  );
}
